/**
 * Badge generator for README files
 */

import type { AnalysisResult } from '../types/index.js';

interface BadgeOptions {
  style?: 'flat' | 'flat-square' | 'for-the-badge' | 'plastic';
  label?: string;
}

/**
 * Generates a shields.io badge URL for install time
 */
export function generateBadgeUrl(result: AnalysisResult, options: BadgeOptions = {}): string {
  const { style = 'flat', label = 'install time' } = options;

  const time = result.estimatedTotalTime;
  const color = getColorForTime(time);
  const timeText = formatTimeForBadge(time);

  // URL encode for shields.io
  const encodedLabel = encodeURIComponent(label);
  const encodedTime = encodeURIComponent(timeText);

  return `https://img.shields.io/badge/${encodedLabel}-${encodedTime}-${color}?style=${style}`;
}

/**
 * Generates markdown for badge
 */
export function generateBadgeMarkdown(result: AnalysisResult, options: BadgeOptions = {}): string {
  const url = generateBadgeUrl(result, options);
  return `![Install Time](${url})`;
}

/**
 * Generates HTML for badge
 */
export function generateBadgeHtml(result: AnalysisResult, options: BadgeOptions = {}): string {
  const url = generateBadgeUrl(result, options);
  return `<img alt="Install Time" src="${url}" />`;
}

/**
 * Generates full badge snippet with all formats
 */
export function generateBadgeSnippets(result: AnalysisResult): {
  url: string;
  markdown: string;
  html: string;
  summary: string;
} {
  const time = result.estimatedTotalTime;
  const slowCount = result.slowPackages.length;

  const summary = time === 0
    ? 'No slow packages detected - your dependencies are optimized!'
    : `Found ${slowCount} slow package${slowCount === 1 ? '' : 's'} adding ~${formatTimeForBadge(time)} to install time`;

  return {
    url: generateBadgeUrl(result),
    markdown: generateBadgeMarkdown(result),
    html: generateBadgeHtml(result),
    summary,
  };
}

/**
 * Gets badge color based on install time
 */
function getColorForTime(seconds: number): string {
  if (seconds === 0) return 'brightgreen';
  if (seconds < 30) return 'green';
  if (seconds < 60) return 'yellow';
  if (seconds < 120) return 'orange';
  return 'red';
}

/**
 * Formats time for badge display
 */
function formatTimeForBadge(seconds: number): string {
  if (seconds === 0) return 'fast';
  if (seconds < 60) return `~${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  const secs = seconds % 60;
  if (secs === 0) return `~${minutes}m`;
  return `~${minutes}m ${secs}s`;
}

/**
 * Generates a comprehensive install report for CI
 */
export function generateCIReport(result: AnalysisResult): string {
  const lines: string[] = [
    '# npm-why-slow Analysis Report',
    '',
    `**Total packages analyzed:** ${result.totalPackages}`,
    `**Slow packages found:** ${result.slowPackages.length}`,
    `**Estimated slow time:** ${formatTimeForBadge(result.estimatedTotalTime)}`,
    `**Potential savings:** ${formatTimeForBadge(result.potentialSavings)}`,
    '',
  ];

  if (result.slowPackages.length > 0) {
    lines.push('## Slow Packages');
    lines.push('');
    lines.push('| Package | Est. Time | Reason |');
    lines.push('|---------|-----------|--------|');

    for (const pkg of result.slowPackages) {
      lines.push(`| ${pkg.name} | ~${pkg.estimatedTime}s | ${pkg.reason || 'unknown'} |`);
    }

    lines.push('');
  }

  if (result.suggestions.length > 0) {
    lines.push('## Suggestions');
    lines.push('');

    for (const suggestion of result.suggestions) {
      const icon = suggestion.priority === 'high' ? ':fire:' : suggestion.priority === 'medium' ? ':zap:' : ':bulb:';
      lines.push(`- ${icon} ${suggestion.suggestion} (saves ~${suggestion.potentialSavings}s)`);
    }

    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [npm-why-slow](https://github.com/willzhangfly/npm-why-slow)*');

  return lines.join('\n');
}
